### ISSUE TITLE
Cannot read system files

### ISSUE THREAD

**Issue by sirde** [ALLTERCO/cc3200tool#10]
Thanks for the tool! It's a pity that TI does not provide a way to program the device in CLI.

When I do a format or a write file there is no error, but when I try to read a file it returns: "/sys/mcuimg.bin does not exist on target"

Do you have any idea what could be the source of the issue?

See the whole logs below if it can help:

C:\Users\cedric\AppData\Local\Programs\Python\Python36\python.exe C:/workspace/cc3200tool/cc3200tool/cc.py -p COM3 --sop2 ~dtr --reset ~rts read_file /sys/mcuimg.bin -
2017-11-13 11:02:50,561 -- Connecting to target...
2017-11-13 11:02:55,863 -- timed out while waiting for ack
2017-11-13 11:02:56,065 -- Connected, reading version...
2017-11-13 11:02:56,067 -- connected to target
2017-11-13 11:02:56,067 -- Version: CC3x00VersionInfo(<memory at 0x000001C98E529AC8>, <memory at 0x000001C98E529B88>, <memory at 0x000001C98E529C48>, <memory at 0x000001C98E529D08>, <memory at 0x000001C98E529DC8>)
2017-11-13 11:02:56,067 -- This is a CC3200 device
2017-11-13 11:02:56,067 -- Switching to NWP bootloader...
2017-11-13 11:02:56,082 -- Switching UART to APPS...
2017-11-13 11:02:56,098 -- Resetting communications ...
2017-11-13 11:02:57,314 -- Uploading rbtl3100s.dll...
2017-11-13 11:02:57,315 -- Getting storage list...
2017-11-13 11:02:57,332 -- Getting storage info...
2017-11-13 11:02:57,346 -- storage info bytes: 0x10, 0x0, 0x0, 0x10, 0x0, 0x0, 0x0, 0x0
2017-11-13 11:02:58,050 -- APPS version: CC3x00VersionInfo(<memory at 0x000001C98E97E288>, <memory at 0x000001C98E97E348>, <memory at 0x000001C98E97E408>, <memory at 0x000001C98E97E4C8>, <memory at 0x000001C98E97E588>)
Traceback (most recent call last):
  File "C:/workspace/cc3200tool/cc3200tool/cc.py", line 813, in <module>
    main()
  File "C:/workspace/cc3200tool/cc3200tool/cc.py", line 801, in main
    cc.read_file(command.cc_filename, command.local_file)
  File "C:/workspace/cc3200tool/cc3200tool/cc.py", line 694, in read_file
    raise CC3200Error("{} does not exist on target".format(cc_fname))
__main__.CC3200Error: /sys/mcuimg.bin does not exist on target

On a related subject, In Uniflash there is the option to "List file System". Is it possible to implement this without too much reverse engineering?

**Comment by kzyapkov** [comment]
Listing the filesystem is a pain -- you have to fetch the allocation table and parse it yourself, and it's not documented anywhere, so ... just use Unicrap for that.

The error looks like the normal output when the file actually doesn't exist on the target. See if 9e44542 fixes that.

Also, try to install the tool with pip and use the generated binary instead of running the python module directly. The tool relies on `pkgutil` for access to some binaries we had to pull from TI's tools.

**Comment by sirde** [comment]
Thanks for the quick feedback!

The dll install was ok, but I was using the unmerged PR for python 3...  It's now fine on python 2.7.
