### ISSUE TITLE
cc3200tool cannot run on Windows 7 64-bit laptop.

### ISSUE THREAD

**Issue by nick-yang-nj** [ALLTERCO/cc3200tool#4]
Hi,

I am trying this cc3200tool on Windows 7 64-bit laptop and got an issue. The following is the message. Should it work on Windows machine?

Thanks,

Nick
--------------------------------------------------------------
2017-02-02 15:04:02,364 -- Connecting to target...
2017-02-02 15:04:02,566 -- Connected, reading version...
2017-02-02 15:04:02,566 -- connected to target
2017-02-02 15:04:02,566 -- Version: CC3x00VersionInfo((0, 4, 1, 2), (0, 0, 0, 0), (0, 0, 0, 0), (0, 0, 0, 0), (16, 0, 0, 0))
2017-02-02 15:04:02,566 -- This is a CC3200 device
2017-02-02 15:04:02,582 -- Switching to NWP bootloader...
2017-02-02 15:04:02,582 -- Switching UART to APPS...
2017-02-02 15:04:02,598 -- Resetting communications ...
2017-02-02 15:04:03,815 -- Uploading rbtl3100s.dll...
2017-02-02 15:04:03,815 -- Getting storage list...
2017-02-02 15:04:03,831 -- Getting storage info...
2017-02-02 15:04:03,845 -- storage info bytes: 0x10, 0x0, 0x0, 0x10, 0x0, 0x0, 0x0, 0x0
Traceback (most recent call last):
  File "cc3200tool.py", line 761, in <module>
  File "cc3200tool.py", line 737, in main
  File "cc3200tool.py", line 545, in switch_to_nwp_bootloader
  File "cc3200tool.py", line 440, in _raw_write
TypeError: object of type 'NoneType' has no len()
Failed to execute script cc3200tool

**Comment by kzyapkov** [comment]
The tool cannot find the binary blobs from TI needed for this to work. What method did you use to install the package? Can you see the `dll/*.dll` files distributed with this tool on your filesystem?
